from googleapiclient.discovery import build

from config import DAILY_SEND_LIMIT, SHEET_RANGE
from google_auth import get_credentials

# Column order: Name, Email, Company, Status, ThreadID, SentAt, EmailBody, LeadReason, EmailConfidence
(
    COL_NAME, COL_EMAIL, COL_COMPANY, COL_STATUS, COL_THREAD_ID, COL_SENT_AT, COL_EMAIL_BODY,
    COL_LEAD_REASON, COL_EMAIL_CONFIDENCE,
) = range(9)


def _get_service(account):
    # Not cached: credentials differ per account, and the underlying
    # httplib2.Http connection isn't safe to share across threads.
    return build("sheets", "v4", credentials=get_credentials(account))


def _sheet_id(account):
    sheet_id = (account.get("google_sheet_id") or "").strip()
    if not sheet_id:
        raise RuntimeError("This account hasn't connected a Google Sheet yet")
    return sheet_id


def get_all_rows(account):
    """Returns list of (row_index, row_values). row_index is 1-based sheet row number."""
    service = _get_service(account)
    result = (
        service.spreadsheets()
        .values()
        .get(spreadsheetId=_sheet_id(account), range=SHEET_RANGE)
        .execute()
    )
    values = result.get("values", [])
    rows = []
    for i, row in enumerate(values[1:], start=2):  # skip header row, sheet rows are 1-based
        padded = row + [""] * (9 - len(row))
        rows.append((i, padded))
    return rows


def get_pending_rows(account):
    """Rows approved for sending but not yet sent."""
    return [(idx, row) for idx, row in get_all_rows(account) if not row[COL_STATUS].strip()]


def sent_in_last_24_hours(rows):
    """Count timestamps generated by this app in the preceding 24 hours."""
    from datetime import datetime, timedelta, timezone

    cutoff = datetime.now(timezone.utc) - timedelta(days=1)
    total = 0
    for _, row in rows:
        value = row[COL_SENT_AT].strip()
        if not value:
            continue
        try:
            sent_at = datetime.fromisoformat(value.replace("Z", "+00:00"))
            if sent_at.tzinfo is None:
                sent_at = sent_at.replace(tzinfo=timezone.utc)
            if sent_at >= cutoff:
                total += 1
        except ValueError:
            # Imported/manual timestamps are not trusted as evidence that this
            # app sent a message; they never make an address eligible either.
            continue
    return total


def campaign_readiness(account):
    """Return the current sendable rows and the conservative daily allowance.

    Sendable means: approved (blank Status) and has an email address. There's
    no verification gate -- the sheet owner is trusted to only approve leads
    they're comfortable emailing.
    """
    rows = get_all_rows(account)
    eligible = [(idx, row) for idx, row in rows if not row[COL_STATUS].strip() and row[COL_EMAIL].strip()]
    sent_today = sent_in_last_24_hours(rows)
    remaining = max(0, DAILY_SEND_LIMIT - sent_today)
    return {
        "eligible": eligible[:remaining],
        "eligible_total": len(eligible),
        "sent_today": sent_today,
        "daily_limit": DAILY_SEND_LIMIT,
        "remaining_today": remaining,
        "capped": max(0, len(eligible) - remaining),
    }


def get_reply_check_rows(account):
    """Rows that could have a new reply worth checking: both "Sent" (no reply
    yet) and "Replied" (a reply already came in, but a conversation can have
    more than one message -- a "Replied" row must stay in scope or a second
    message on the same thread is never looked at again)."""
    return [
        (idx, row) for idx, row in get_all_rows(account)
        if row[COL_STATUS].strip() in ("Sent", "Replied")
    ]


def _row_update_cells(row_index, status=None, thread_id=None, sent_at=None, email_body=None, email_confidence=None):
    cells = []
    if status is not None:
        cells.append((f"D{row_index}", status))
    if thread_id is not None:
        cells.append((f"E{row_index}", thread_id))
    if sent_at is not None:
        cells.append((f"F{row_index}", sent_at))
    if email_body is not None:
        cells.append((f"G{row_index}", email_body))
    if email_confidence is not None:
        cells.append((f"I{row_index}", email_confidence))
    return cells


def update_row(account, row_index, status=None, thread_id=None, sent_at=None, email_body=None, email_confidence=None):
    cells = _row_update_cells(row_index, status, thread_id, sent_at, email_body, email_confidence)
    if not cells:
        return

    _get_service(account).spreadsheets().values().batchUpdate(
        spreadsheetId=_sheet_id(account),
        body={
            "valueInputOption": "RAW",
            "data": [{"range": cell_range, "values": [[value]]} for cell_range, value in cells],
        },
    ).execute()


def batch_update_rows(account, updates):
    """updates: list of dicts with row_index and any of status/thread_id/sent_at/email_body.
    Writes every row in one API round-trip instead of one call per row."""
    cells = [
        cell
        for u in updates
        for cell in _row_update_cells(
            u["row_index"], u.get("status"), u.get("thread_id"), u.get("sent_at"), u.get("email_body"), u.get("email_confidence")
        )
    ]
    if not cells:
        return

    _get_service(account).spreadsheets().values().batchUpdate(
        spreadsheetId=_sheet_id(account),
        body={
            "valueInputOption": "RAW",
            "data": [{"range": cell_range, "values": [[value]]} for cell_range, value in cells],
        },
    ).execute()


def append_rows(account, rows):
    """rows: list of 9-value lists, in COL_* order. Appended after the last row."""
    if not rows:
        return
    service = _get_service(account)
    service.spreadsheets().values().append(
        spreadsheetId=_sheet_id(account),
        range=SHEET_RANGE,
        valueInputOption="RAW",
        insertDataOption="INSERT_ROWS",
        body={"values": rows},
    ).execute()
