from googleapiclient.discovery import build

from config import DAILY_SEND_LIMIT, SHEET_RANGE
from google_auth import get_credentials

# Column order: Name, Email, Company, Status, ThreadID, SentAt, EmailBody, LeadReason, EmailConfidence
(
    COL_NAME, COL_EMAIL, COL_COMPANY, COL_STATUS, COL_THREAD_ID, COL_SENT_AT, COL_EMAIL_BODY,
    COL_LEAD_REASON, COL_EMAIL_CONFIDENCE,
) = range(9)


def _get_service(account):
    # Not cached: credentials differ per account, and the underlying
    # httplib2.Http connection isn't safe to share across threads.
    return build("sheets", "v4", credentials=get_credentials(account))


def _sheet_id(account):
    sheet_id = (account.get("google_sheet_id") or "").strip()
    if not sheet_id:
        raise RuntimeError("This account hasn't connected a Google Sheet yet")
    return sheet_id


EXPECTED_HEADER = [
    "Name", "Email", "Company", "Status", "ThreadID", "SentAt", "EmailBody",
    "LeadReason", "EmailConfidence",
]


def _validate_header(values):
    """Fails loudly when the sheet's header row doesn't match the expected
    columns. Every read and write in this module addresses columns by
    position, so a reordered or renamed header would otherwise cause silently
    wrong behavior (emailing the wrong field, statuses in the wrong column) --
    a worse failure mode than a clear error naming the fix.

    Only the cells actually present in row 1 are checked, as a prefix of the
    expected header (at least Name, Email): real sheets in the wild -- the
    founder's own included -- often only carry the first few header cells,
    and columns still line up positionally. What must never pass is a
    reordered or foreign layout ("Email, Name, ..." / "First Name, ...")."""
    if not values:
        raise RuntimeError(
            "The connected sheet is empty. Row 1 must be this header: "
            + ", ".join(EXPECTED_HEADER)
        )
    found = [cell.strip().lower() for cell in values[0][:9]]
    while found and not found[-1]:
        found.pop()
    expected = [name.lower() for name in EXPECTED_HEADER]
    if len(found) < 2 or found != expected[:len(found)]:
        raise RuntimeError(
            "The sheet's header row doesn't match what Agent Hub expects. "
            f"Row 1 must start with: {', '.join(EXPECTED_HEADER[:2])} (full header: "
            f"{', '.join(EXPECTED_HEADER)}) — found: "
            f"{', '.join(cell for cell in values[0][:9] if cell.strip()) or '(blank)'}"
        )


def get_all_rows(account):
    """Returns list of (row_index, row_values). row_index is 1-based sheet row number."""
    service = _get_service(account)
    result = (
        service.spreadsheets()
        .values()
        .get(spreadsheetId=_sheet_id(account), range=SHEET_RANGE)
        .execute()
    )
    values = result.get("values", [])
    _validate_header(values)
    rows = []
    for i, row in enumerate(values[1:], start=2):  # skip header row, sheet rows are 1-based
        padded = row + [""] * (9 - len(row))
        rows.append((i, padded))
    return rows


def get_pending_rows(account):
    """Rows approved for sending but not yet sent."""
    return [(idx, row) for idx, row in get_all_rows(account) if not row[COL_STATUS].strip()]


def sent_in_last_24_hours(rows):
    """Count timestamps generated by this app in the preceding 24 hours."""
    from datetime import datetime, timedelta, timezone

    cutoff = datetime.now(timezone.utc) - timedelta(days=1)
    total = 0
    for _, row in rows:
        value = row[COL_SENT_AT].strip()
        if not value:
            continue
        try:
            sent_at = datetime.fromisoformat(value.replace("Z", "+00:00"))
            if sent_at.tzinfo is None:
                sent_at = sent_at.replace(tzinfo=timezone.utc)
            if sent_at >= cutoff:
                total += 1
        except ValueError:
            # Imported/manual timestamps are not trusted as evidence that this
            # app sent a message; they never make an address eligible either.
            continue
    return total


def campaign_readiness(account):
    """Return the current sendable rows and the conservative daily allowance.

    Sendable means: approved (blank Status) and has an email address. There's
    no verification gate -- the sheet owner is trusted to only approve leads
    they're comfortable emailing.
    """
    rows = get_all_rows(account)
    eligible = [(idx, row) for idx, row in rows if not row[COL_STATUS].strip() and row[COL_EMAIL].strip()]
    sent_today = sent_in_last_24_hours(rows)
    remaining = max(0, DAILY_SEND_LIMIT - sent_today)
    return {
        "eligible": eligible[:remaining],
        "eligible_total": len(eligible),
        "sent_today": sent_today,
        "daily_limit": DAILY_SEND_LIMIT,
        "remaining_today": remaining,
        "capped": max(0, len(eligible) - remaining),
    }


def get_reply_check_rows(account):
    """Rows that could have a new reply worth checking: both "Sent" (no reply
    yet) and "Replied" (a reply already came in, but a conversation can have
    more than one message -- a "Replied" row must stay in scope or a second
    message on the same thread is never looked at again)."""
    return [
        (idx, row) for idx, row in get_all_rows(account)
        if row[COL_STATUS].strip() in ("Sent", "Replied")
    ]


def _row_update_cells(row_index, status=None, thread_id=None, sent_at=None, email_body=None, email_confidence=None):
    cells = []
    if status is not None:
        cells.append((f"D{row_index}", status))
    if thread_id is not None:
        cells.append((f"E{row_index}", thread_id))
    if sent_at is not None:
        cells.append((f"F{row_index}", sent_at))
    if email_body is not None:
        cells.append((f"G{row_index}", email_body))
    if email_confidence is not None:
        cells.append((f"I{row_index}", email_confidence))
    return cells


def require_full_header(account):
    """Gate for every WRITE path (send batch, reply marking, lead
    approve/discard): row 1 must carry all nine labels before the app writes
    into columns D-I. Reads accept a Name+Email prefix (_validate_header),
    but writing into unlabeled columns could silently overwrite data the
    owner keeps there -- the full header is their explicit consent that
    those columns belong to Agent Hub. The error hands them the exact row
    to paste."""
    service = _get_service(account)
    result = (
        service.spreadsheets()
        .values()
        .get(spreadsheetId=_sheet_id(account), range="A1:I1")
        .execute()
    )
    values = result.get("values", [])
    header = [cell.strip().lower() for cell in (values[0] if values else [])]
    if header != [name.lower() for name in EXPECTED_HEADER]:
        raise RuntimeError(
            "Before Agent Hub can write statuses, row 1 must contain the full "
            "header (this protects any data you keep in unlabeled columns). "
            "Paste this into row 1: " + ", ".join(EXPECTED_HEADER) + ". "
            "Starting a fresh sheet? Settings has a starter file to download "
            "with the header already in place."
        )


def _verify_row_index(account, row_index, expect_email):
    """Guards status writes against stale row indexes. Row numbers are
    captured when the sheet is read; if the owner sorts or inserts rows
    before the write lands, the index now points at a different contact and
    the write would corrupt their row. Re-reads the sheet: if the expected
    email still lives at row_index, use it; if it moved, follow it; if it's
    gone, fail loudly rather than write into the wrong row."""
    wanted = expect_email.strip().lower()
    rows = get_all_rows(account)
    for idx, row in rows:
        if idx == row_index and row[COL_EMAIL].strip().lower() == wanted:
            return row_index
    for idx, row in rows:
        if row[COL_EMAIL].strip().lower() == wanted:
            return idx
    raise RuntimeError(
        f"Couldn't find {expect_email} in the sheet anymore — it may have been "
        "edited or the row deleted. No status was written for this contact."
    )


def update_row(account, row_index, status=None, thread_id=None, sent_at=None, email_body=None, email_confidence=None, expect_email=None):
    if expect_email:
        row_index = _verify_row_index(account, row_index, expect_email)
    cells = _row_update_cells(row_index, status, thread_id, sent_at, email_body, email_confidence)
    if not cells:
        return

    _get_service(account).spreadsheets().values().batchUpdate(
        spreadsheetId=_sheet_id(account),
        body={
            "valueInputOption": "RAW",
            "data": [{"range": cell_range, "values": [[value]]} for cell_range, value in cells],
        },
    ).execute()


def append_rows(account, rows):
    """rows: list of 9-value lists, in COL_* order. Appended after the last row."""
    if not rows:
        return
    service = _get_service(account)
    service.spreadsheets().values().append(
        spreadsheetId=_sheet_id(account),
        range=SHEET_RANGE,
        valueInputOption="RAW",
        insertDataOption="INSERT_ROWS",
        body={"values": rows},
    ).execute()
