-- Canonical Sendkeep schema baseline.
--
-- This migration is deliberately idempotent. It creates a clean project and
-- reconciles projects that were previously maintained with README snippets.
-- It never drops a table or customer data. Future schema changes belong in a
-- new timestamped migration; do not edit this file after it has been deployed.

create extension if not exists pgcrypto;

create table if not exists public.accounts (
    id uuid primary key default gen_random_uuid(),
    email text not null unique,
    google_id text unique,
    google_token text,
    google_sheet_id text,
    sender_name text not null default 'the team',
    sender_company text not null default '',
    meeting_purpose text not null default 'a quick intro call to see if there''s a fit to work together',
    custom_instructions text not null default '',
    outreach_send_mode text not null default 'manual',
    follow_up_delay_days integer not null default 3,
    calendar_booking_link text,
    notify_email text,
    bounce_ack_count integer not null default 0,
    plan text not null default 'trial',
    worker_heartbeat_at timestamptz,
    last_error text,
    created_at timestamptz not null default now()
);

alter table public.accounts
    add column if not exists google_id text,
    add column if not exists sender_company text not null default '',
    add column if not exists custom_instructions text not null default '',
    add column if not exists outreach_send_mode text not null default 'manual',
    add column if not exists follow_up_delay_days integer not null default 3,
    add column if not exists bounce_ack_count integer not null default 0,
    add column if not exists plan text not null default 'trial',
    add column if not exists worker_heartbeat_at timestamptz,
    add column if not exists last_error text;

create unique index if not exists accounts_google_id_key
    on public.accounts (google_id) where google_id is not null;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'accounts_outreach_send_mode_check'
    ) then
        alter table public.accounts add constraint accounts_outreach_send_mode_check
            check (outreach_send_mode in ('manual', 'auto'));
    end if;
    if not exists (
        select 1 from pg_constraint where conname = 'accounts_follow_up_delay_days_check'
    ) then
        alter table public.accounts add constraint accounts_follow_up_delay_days_check
            check (follow_up_delay_days between 1 and 14);
    end if;
end $$;

create table if not exists public.usage_events (
    id bigint generated always as identity primary key,
    account_id uuid not null references public.accounts(id) on delete cascade,
    kind text not null,
    detail text not null default '',
    quantity integer not null default 1,
    created_at timestamptz not null default now()
);
create index if not exists usage_events_account_idx
    on public.usage_events (account_id, created_at);

create table if not exists public.outreach_drafts (
    id bigint generated always as identity primary key,
    account_id uuid not null references public.accounts(id) on delete cascade,
    row_index integer not null,
    name text not null default '',
    email text not null default '',
    company text not null default '',
    subject text not null default '',
    body text not null default '',
    original_subject text,
    original_body text,
    rewritten boolean not null default false,
    status text not null default 'pending',
    sent_at timestamptz,
    thread_id text,
    follow_up_due_at timestamptz,
    follow_up_status text,
    follow_up_cancel_reason text,
    follow_up_sent_at timestamptz,
    follow_up_replied_at timestamptz,
    created_at timestamptz not null default now()
);
alter table public.outreach_drafts
    add column if not exists original_subject text,
    add column if not exists original_body text,
    add column if not exists rewritten boolean not null default false,
    add column if not exists sent_at timestamptz,
    add column if not exists thread_id text,
    add column if not exists follow_up_due_at timestamptz,
    add column if not exists follow_up_status text,
    add column if not exists follow_up_cancel_reason text,
    add column if not exists follow_up_sent_at timestamptz,
    add column if not exists follow_up_replied_at timestamptz;
create index if not exists outreach_drafts_account_status_idx
    on public.outreach_drafts (account_id, status);
create unique index if not exists outreach_drafts_pending_row_idx
    on public.outreach_drafts (account_id, row_index) where status = 'pending';
create index if not exists outreach_drafts_sent_at_idx
    on public.outreach_drafts (account_id, status, sent_at);
create index if not exists outreach_follow_up_status_idx
    on public.outreach_drafts (account_id, follow_up_status, follow_up_due_at);

create table if not exists public.reviews (
    id bigint generated always as identity primary key,
    account_id uuid not null references public.accounts(id) on delete cascade,
    row_index integer,
    name text not null default '',
    email text not null default '',
    thread_id text not null default '',
    customer_reply text not null default '',
    draft_reply text not null default '',
    original_draft_reply text,
    sent_at timestamptz,
    status text not null default 'pending',
    gmail_message_id text,
    validator_problems text,
    degraded_classification boolean not null default false,
    rewritten boolean not null default false,
    kind text not null default 'reply',
    source_draft_id bigint references public.outreach_drafts(id) on delete cascade,
    created_at timestamptz not null default now()
);
alter table public.reviews
    add column if not exists original_draft_reply text,
    add column if not exists sent_at timestamptz,
    add column if not exists gmail_message_id text,
    add column if not exists validator_problems text,
    add column if not exists degraded_classification boolean not null default false,
    add column if not exists rewritten boolean not null default false,
    add column if not exists kind text not null default 'reply',
    add column if not exists source_draft_id bigint references public.outreach_drafts(id) on delete cascade;
alter table public.reviews alter column row_index drop not null;
update public.reviews set row_index = null where row_index = 0;
create index if not exists reviews_account_status_idx
    on public.reviews (account_id, status);
create unique index if not exists reviews_thread_message_idx
    on public.reviews (account_id, thread_id, gmail_message_id)
    where gmail_message_id is not null;
create unique index if not exists reviews_one_follow_up_idx
    on public.reviews (account_id, source_draft_id) where kind = 'follow_up';

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.reviews'::regclass
          and conname = 'reviews_kind_check'
    ) then
        alter table public.reviews add constraint reviews_kind_check
            check (kind in ('reply', 'follow_up'));
    end if;
end $$;

create table if not exists public.suppressions (
    id bigint generated always as identity primary key,
    account_id uuid not null references public.accounts(id) on delete cascade,
    email text not null,
    source text not null default 'unsubscribe_link',
    created_at timestamptz not null default now(),
    unique (account_id, email)
);

create table if not exists public.tracked_threads (
    id bigint generated always as identity primary key,
    account_id uuid not null references public.accounts(id) on delete cascade,
    thread_id text not null,
    email text not null default '',
    name text not null default '',
    company text not null default '',
    row_index integer,
    source text not null,
    status text not null default 'active',
    last_contact_message_id text,
    last_checked_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (account_id, thread_id)
);
create index if not exists tracked_threads_account_status_idx
    on public.tracked_threads (account_id, status);

create table if not exists public.commitments (
    id bigint generated always as identity primary key,
    account_id uuid not null references public.accounts(id) on delete cascade,
    thread_id text not null,
    source_message_id text not null,
    actor text not null check (actor in ('contact', 'operator')),
    commitment_type text not null,
    action_text text not null,
    due_at timestamptz,
    due_text text not null default '',
    evidence text not null default '',
    confidence numeric not null check (confidence >= 0 and confidence <= 1),
    status text not null default 'detected',
    estimated_value numeric,
    dismissal_reason text,
    reminder_at timestamptz,
    confirmed_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (account_id, source_message_id, commitment_type, action_text)
);
alter table public.commitments
    add column if not exists estimated_value numeric,
    add column if not exists dismissal_reason text;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.commitments'::regclass
          and conname = 'commitments_status_check'
    ) then
        alter table public.commitments add constraint commitments_status_check
            check (status in ('detected', 'confirmed', 'due', 'queued',
                              'completed', 'dismissed', 'expired'));
    end if;
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.commitments'::regclass
          and conname = 'commitments_dismissal_reason_check'
    ) then
        alter table public.commitments add constraint commitments_dismissal_reason_check
            check (dismissal_reason is null or dismissal_reason in ('incorrect', 'not_applicable'));
    end if;
end $$;
create index if not exists commitments_account_status_idx
    on public.commitments (account_id, status, reminder_at);

create table if not exists public.worker_runs (
    id bigint generated always as identity primary key,
    host_id text not null default '',
    status text not null,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    checked_accounts integer not null default 0,
    skipped_accounts integer not null default 0,
    failed_accounts integer not null default 0,
    degraded_accounts integer not null default 0,
    degraded_reasons jsonb not null default '{}'::jsonb,
    elapsed_seconds numeric not null default 0,
    error text,
    created_at timestamptz not null default now()
);
alter table public.worker_runs
    add column if not exists degraded_accounts integer not null default 0,
    add column if not exists degraded_reasons jsonb not null default '{}'::jsonb;
create index if not exists worker_runs_started_idx
    on public.worker_runs (started_at desc);

create table if not exists public.worker_events (
    id bigint generated always as identity primary key,
    run_id bigint references public.worker_runs(id) on delete cascade,
    account_id uuid references public.accounts(id) on delete cascade,
    event_type text not null,
    status text not null,
    details jsonb not null default '{}'::jsonb,
    dedupe_key text,
    created_at timestamptz not null default now()
);
alter table public.worker_events add column if not exists dedupe_key text;
create index if not exists worker_events_account_created_idx
    on public.worker_events (account_id, created_at desc);
create unique index if not exists worker_events_dedupe_idx
    on public.worker_events (account_id, event_type, dedupe_key)
    where dedupe_key is not null;
-- PostgREST's on_conflict=column-list cannot infer a partial unique index.
-- Keep the historical partial index above for existing consumers, but provide
-- non-partial indexes for the writer's conflict targets. Nullable columns are
-- intentional: PostgreSQL permits multiple NULLs, while every emitted event
-- supplies a non-null dedupe_key.
create unique index if not exists worker_events_account_dedupe_unique_idx
    on public.worker_events (account_id, event_type, dedupe_key);
create unique index if not exists worker_events_run_dedupe_unique_idx
    on public.worker_events (run_id, event_type, dedupe_key)
;

-- The application startup gate needs to verify invariants that PostgREST's
-- OpenAPI document cannot describe (RLS, indexes, and check constraints). Keep
-- that introspection in one protected RPC so boot still makes one request and
-- receives a single, catalog-backed contract snapshot.
create or replace function public.sendkeep_schema_contract()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
    return jsonb_build_object(
        'version', '20260827000000_sendkeep_baseline',
        'columns', jsonb_build_object(
            'accounts.bounce_ack_count', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'accounts' and column_name = 'bounce_ack_count'),
            'accounts.plan', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'accounts' and column_name = 'plan'),
            'accounts.worker_heartbeat_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'accounts' and column_name = 'worker_heartbeat_at'),
            'reviews.gmail_message_id', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'gmail_message_id'),
            'reviews.original_draft_reply', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'original_draft_reply'),
            'reviews.sent_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'sent_at'),
            'reviews.validator_problems', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'validator_problems'),
            'reviews.degraded_classification', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'degraded_classification'),
            'reviews.rewritten', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'rewritten'),
            'reviews.kind', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'kind'),
            'reviews.row_index', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'row_index'),
            'outreach_drafts.original_subject', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'outreach_drafts' and column_name = 'original_subject'),
            'outreach_drafts.original_body', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'outreach_drafts' and column_name = 'original_body'),
            'outreach_drafts.rewritten', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'outreach_drafts' and column_name = 'rewritten'),
            'outreach_drafts.sent_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'outreach_drafts' and column_name = 'sent_at'),
            'outreach_drafts.follow_up_status', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'outreach_drafts' and column_name = 'follow_up_status'),
            'tracked_threads.id', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'tracked_threads' and column_name = 'id'),
            'commitments.id', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'commitments' and column_name = 'id'),
            'commitments.estimated_value', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'commitments' and column_name = 'estimated_value'),
            'commitments.dismissal_reason', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'commitments' and column_name = 'dismissal_reason'),
            'worker_runs.id', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'worker_runs' and column_name = 'id'),
            'worker_runs.degraded_accounts', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'worker_runs' and column_name = 'degraded_accounts'),
            'worker_runs.degraded_reasons', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'worker_runs' and column_name = 'degraded_reasons'),
            'worker_events.id', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'worker_events' and column_name = 'id'),
            'worker_events.dedupe_key', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'worker_events' and column_name = 'dedupe_key')
        ),
        'nullable', jsonb_build_object(
            'reviews.row_index', coalesce((select is_nullable = 'YES' from information_schema.columns where table_schema = 'public' and table_name = 'reviews' and column_name = 'row_index'), false)
        ),
        'indexes', jsonb_build_object(
            'reviews_thread_message_idx', exists (
                select 1 from pg_indexes
                where schemaname = 'public'
                  and indexname = 'reviews_thread_message_idx'
                  and indexdef ilike '%(account_id, thread_id, gmail_message_id)%'
                  and indexdef ilike '%gmail_message_id is not null%'
            ),
            'worker_events_account_dedupe_unique_idx', exists (
                select 1 from pg_indexes
                where schemaname = 'public'
                  and indexname = 'worker_events_account_dedupe_unique_idx'
                  and indexdef ilike '%(account_id, event_type, dedupe_key)%'
                  and position(' where ' in lower(indexdef)) = 0
            ),
            'worker_events_run_dedupe_unique_idx', exists (
                select 1 from pg_indexes
                where schemaname = 'public'
                  and indexname = 'worker_events_run_dedupe_unique_idx'
                  and indexdef ilike '%(run_id, event_type, dedupe_key)%'
                  and position(' where ' in lower(indexdef)) = 0
            )
        ),
        'rls', jsonb_build_object(
            'accounts', coalesce((select relrowsecurity from pg_class where oid = 'public.accounts'::regclass), false),
            'reviews', coalesce((select relrowsecurity from pg_class where oid = 'public.reviews'::regclass), false),
            'usage_events', coalesce((select relrowsecurity from pg_class where oid = 'public.usage_events'::regclass), false),
            'outreach_drafts', coalesce((select relrowsecurity from pg_class where oid = 'public.outreach_drafts'::regclass), false),
            'suppressions', coalesce((select relrowsecurity from pg_class where oid = 'public.suppressions'::regclass), false),
            'tracked_threads', coalesce((select relrowsecurity from pg_class where oid = 'public.tracked_threads'::regclass), false),
            'commitments', coalesce((select relrowsecurity from pg_class where oid = 'public.commitments'::regclass), false),
            'worker_runs', coalesce((select relrowsecurity from pg_class where oid = 'public.worker_runs'::regclass), false),
            'worker_events', coalesce((select relrowsecurity from pg_class where oid = 'public.worker_events'::regclass), false)
        ),
        'constraints', jsonb_build_object(
            'reviews_kind_check', exists (select 1 from pg_constraint where conrelid = 'public.reviews'::regclass and conname = 'reviews_kind_check'),
            'commitments_status_check', exists (select 1 from pg_constraint where conrelid = 'public.commitments'::regclass and conname = 'commitments_status_check'),
            'commitments_dismissal_reason_check', exists (select 1 from pg_constraint where conrelid = 'public.commitments'::regclass and conname = 'commitments_dismissal_reason_check')
        )
    );
end;
$$;
revoke all on function public.sendkeep_schema_contract() from public, anon, authenticated;
grant execute on function public.sendkeep_schema_contract() to service_role;

do $$
declare table_name text;
begin
    foreach table_name in array array[
        'accounts', 'reviews', 'usage_events', 'outreach_drafts',
        'suppressions', 'tracked_threads', 'commitments',
        'worker_runs', 'worker_events'
    ] loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format('revoke all on table public.%I from anon, authenticated', table_name);
    end loop;
end $$;

notify pgrst, 'reload schema';
